version: "2.3"
services:
  lichess-challenger:
    cpus: 1
    mem_limit: "1g"
    image: ghcr.io/lynx-chess/lichess-challenger:latest
    volumes:
      - ./lichess-challenger:/lichess-challenger/logs
    environment:
      - LICHESS_API_TOKEN=${LICHESS_API_TOKEN}
      - LICHESS_USERNAME=${LICHESS_USERNAME}
